### ISSUE TITLE
Colour Discussion 1

### ISSUE THREAD

**Issue by as43z** [humans4u/DesignGuidelines#6]
This is the space related to color correction and addition.

The actual palette for the brand is made of only two colours: #6fa9e8 and #b5b5b5, and the library designates a whole color scale for both as a range between 900 to 100, being 500 the main colours.

Furthermore, there exist two other types of colours: Greys and Utility.

**Greys** represent greyscale utilisation and follow the same schema from 900 to 100.
**Utility** colours contains 4 subcategories: failure, warning, success and info. They are structured as the same way but only from 900 to 600.

**Problems**
The secondary and the greyscale are the same palette (with minor variations). A new secondary colour must be picked.

The utility colours palette need an extension for better usage. Right now the colours are too intense and have no bland-to-light intensity (from 500 to 100).

**Comment by danigarfe** [comment]
Fix proposal: in the 02-colors.md file we should be able to visualize the colors for easier usage. We can use placehold.co for that.

For instance, for the #1a3d6e color (light-primary-900) we can add another row with:
![image](https://github.com/humans4u/DesignGuidelines/assets/45384826/e59355fc-a29a-47da-ac82-3b0a1f10102d)

Preview:
![#1a3d6e](https://placehold.co/15x15/1a3d6e/1a3d6e.png)

**Comment by danigarfe** [comment]
@as43z we should have into account the logo and the psichological impression of the different tones when chosing the primary color. 
For instance:
Blue tones express cleanliness, freshness, tranquility, affection, cold and intelligence.
Green tones express stability, security, balance, sustainability and ecology, prosperity and success, tranquility and calm, nature and health.


I propose using green tones as I believe it aligns better with what H4U represents. Also, green tones fit perfectly with grey tones, the current secondary color. Example of green + grey tones palette:

![pinterestdownloader com-1705749447 890926](https://github.com/humans4u/DesignGuidelines/assets/45384826/afd16ce0-e40c-4e19-a22f-9aab192e7742)

Proposed: 
Primary color: Green (#6daa8b)  ![#6daa8b](https://placehold.co/15x15/6daa8b/6daa8b.png)
Secondary color: Grey (#262627)   ![#262627](https://placehold.co/15x15/262627/262627.png)
Whites tone: White (#eff4f1)   ![#eff4f1](https://placehold.co/15x15/eff4f1/eff4f1.png)

Preview: https://huemint.com/brand-2/#palette=6daa8b-262627-eff4f1

Negative preview: https://huemint.com/brand-2/#palette=262627-eff4f1-6daa8b

Website preview: https://huemint.com/website-1/#palette=eff4f1-262627-6daa8b

Dark mode website preview: https://huemint.com/website-1/#palette=262627-eff4f1-6daa8b

**Comment by as43z** [comment]
> Fix proposal: in the 02-colors.md file we should be able to visualize the colors for easier usage. We can use placehold.co for that.
> 
> For instance, for the #1a3d6e color (light-primary-900) we can add another row with: ![image](https://private-user-images.githubusercontent.com/45384826/298277769-e59355fc-a29a-47da-ac82-3b0a1f10102d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTIwNDIsIm5iZiI6MTcwNTc1MTc0MiwicGF0aCI6Ii80NTM4NDgyNi8yOTgyNzc3NjktZTU5MzU1ZmMtYTI5YS00N2RhLWFjODItM2IwYTFmMTAxMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDExNTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NzEwMjE0ZmNlZWExMzQ4NTM5YjJjYzNkZTk3YjhkODVmZDBmZDNjYzNkYmUxZGM4MWYyYjJmZTI3MmVhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tn4zlkeeKXog6NYscu5huAtYOTYTUPgfmRt4N2Ou3TA)
> 
> Preview: ![#1a3d6e](https://camo.githubusercontent.com/a6094ba294311768201e940be03caecf5903917137cb127de9024108223bb19f/68747470733a2f2f706c616365686f6c642e636f2f31357831352f3161336436652f3161336436652e706e67)

@danigarfe I believe there is a row with the color already shown.

<img width="822" alt="imatge" src="https://github.com/humans4u/DesignGuidelines/assets/50268339/b17ee38d-8e22-4840-900d-77fb8021cd44">

**Comment by as43z** [comment]
> @as43z we should have into account the logo and the psichological impression of the different tones when chosing the primary color. For instance: Blue tones express cleanliness, freshness, tranquility, affection, cold and intelligence. Green tones express stability, security, balance, sustainability and ecology, prosperity and success, tranquility and calm, nature and health.
> 
> I propose using green tones as I believe it aligns better with what H4U represents. Also, green tones fit perfectly with grey tones, the current secondary color. Example of green + grey tones palette:
> 
> ![pinterestdownloader com-1705749447 890926](https://private-user-images.githubusercontent.com/45384826/298278493-afd16ce0-e40c-4e19-a22f-9aab192e7742.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTIwNDIsIm5iZiI6MTcwNTc1MTc0MiwicGF0aCI6Ii80NTM4NDgyNi8yOTgyNzg0OTMtYWZkMTZjZTAtZTQwYy00ZTE5LWEyMmYtOWFhYjE5MmU3NzQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDExNTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZTMxYzg0MTQ1YTcxOWQ3ZGE5ZGFlMGYxNzc0NDM2NzlmNTlhNDM1NmU5M2M3MzQxN2RlMjRjYWMyOGU5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RdGQ41RmZ1q-l6qYMCXURnDPiVBZfLH-xz9ZF5zgvZo)
> 
> Proposed: Primary color: Green (#6daa8b) ![#6daa8b](https://camo.githubusercontent.com/01aa311d55f8d5a375738a76b6b2c3e7c13c385571157280ad4e05bd8189639a/68747470733a2f2f706c616365686f6c642e636f2f31357831352f3664616138622f3664616138622e706e67) Secondary color: Grey (#262627) ![#262627](https://camo.githubusercontent.com/945b67f16fd4e8593ea5161f40996d7394353fa32f02bb3b8c22fd7c65a6ff29/68747470733a2f2f706c616365686f6c642e636f2f31357831352f3236323632372f3236323632372e706e67) Whites tone: White (#eff4f1) ![#eff4f1](https://camo.githubusercontent.com/fed0f47e0350f4d0a2d0b4eb72c14ff60aaa478c14053d0d0f10d8e1acfb301d/68747470733a2f2f706c616365686f6c642e636f2f31357831352f6566663466312f6566663466312e706e67)
> 
> Preview: https://huemint.com/brand-2/#palette=6daa8b-262627-eff4f1
> 
> Negative preview: https://huemint.com/brand-2/#palette=262627-eff4f1-6daa8b
> 
> Website preview: https://huemint.com/website-1/#palette=eff4f1-262627-6daa8b
> 
> Dark mode website preview: https://huemint.com/website-1/#palette=262627-eff4f1-6daa8b

@danigarfe, indeed, this colors feel better; Nevertheless, I would like to follow the convention of from 900 to 100. Could you please elaborate a little bit more on how would the whites fit in this table?

Another concern of mine is the extent use of the custom white on platforms... We should not over use it and white/light mode should use white as background (as well as foreground for the relevant contrasts, i.e. black-white, red-white, ...).

**Comment by as43z** [comment]
| Scale Rank | Green | Secondary |
| --- | --- | --- |
| 900 | #25353D | |
| 800 | #365459 | |
| 700 | #487471 | |
| 600 | #5A8F80 | |
| 500 | #6daa8b | |
| 400 | #7EB78E | |
| 300 | #90C393 | |
| 200 | #AACFA3 | |
| 100 | #C4DAB5 | |

I'm postponing the secondary color, I cannot get it to generate a scale.

**Comment by as43z** [comment]
Closing this issue as deadline was yesterday. For a disclosure of the integration, consult the parent v0.1.0 release issue.
